name: Publish package to npm

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    name: Publish the package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Setup the project
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Clean install dependencies
        run: npm ci

      - name: Publish the package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
